---
# Here we use ansible_pkg_mgr over ansible_os_family/ansible_distribution
# for the sake of generalization. 

- name: Installing Pg extensions (apt)
  apt:
    name: "postgresql-contrib-{{postgresql_version}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  when: ansible_pkg_mgr == "apt"
  notify:
    - restart postgresql
  tags: postgresql

- name: Installing Pg extensions (yum)
  yum:
    name: "postgresql{{postgresql_version_terse}}-contrib"
    state: present
  when: ansible_pkg_mgr == "yum"
  notify:
    - restart postgresql
  tags: postgresql