---
- name: Install HA Postgres dependencies for Patroni
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - haproxy
      - ruby-eye
      - watchdog
      - gcc
      - python-dev
  become: yes
  tags: patroni

- name: Upgrade pip
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  tags: patroni
  with_items:
    - pip
    - setuptools

- name: Install main dependencies for Patroni
  pip:
    name: "{{ item }}"
  with_items:
    - psycopg2
    - python-etcd
    - python-consul
    - dnspython
    - boto
    - mock
    - psycopg2
    - PyYAML
    - requests
    - kazoo
    - six
    - dateutils
  tags: patroni

- name: Install dependencies for Patroni with privs
  pip:
    name:
      - psutil
  become: yes
  tags: patroni

- name: Install patronictl dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - click
    - cdiff
    - tzlocal
    - prettytable
  tags: patroni

# Installing using https://rvm.io/
- name: Installing RVM through official distribution
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && curl -sSL https://get.rvm.io | bash -s stable
  become: yes
  tags: patroni

- name: Installing additional tools for Patroni
  gem:
    name: "{{ item }}"
    state: latest
  with_items:
    - eye
    - rvm
  become: true
  tags: patroni

- name: Enable watchdog service
  service:
    name: watchdog
    state: started
    enabled: yes
  tags: patroni, bootup_config

- name: chmod watchdog device file
  file:
    path: /dev/watchdog
    mode: 0666
  tags: patroni, bootup_config
